name: Code Style

on: [pull_request]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install Composer dependencies
      run: composer install

    - name: Run Pint
      run: ./vendor/bin/pint

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply formatting changes
